### ISSUE TITLE
APP Stürzt beim Synchronisieren von gelöschten Räumen ab

### ISSUE THREAD

**Issue by agent4788** [agent4788/SHC_Android_APP#10]
Beim erstellen und aktualisieren konnte ich nichts feststellen, nur beim löschen schmiert die APP ab wenn man gerade mit der APP in dem gelöschten Raum ist und danach in einen anderen wechselt.

    12-09 06:53:13.480 4363-4363/de.rpi_controlcenter.shc E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: de.rpi_controlcenter.shc, PID: 4363
                                                                        java.lang.NullPointerException: Attempt to invokee virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
                                                                            at android.widget.Toast.makeText(Toast.java:285)
                                                                            at de.rpi_controlcenter.shc.Fragment.RoomViewFragment$2$1$1.run(RoomViewFragment.java:144)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5257)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by jsp-email** [comment]
Wo ist in der APP das menü wo man löschen und erstellen kann

**Comment by Dietmar-Franken** [comment]
Ich glaube das existiert noch nicht

**Comment by agent4788** [comment]
über die Android App kannst du nichts löschen, nur über die WebApp
