### ISSUE TITLE
Fehler beim aktualllisieren

### ISSUE THREAD

**Issue by Dietmar-Franken** [agent4788/SHC_Android_APP#8]
Wenn man in der Weboberfäche einen neuen Raum anlegt und dann in der App auf aktuallisiren geht stüzt sie ab.

**Comment by agent4788** [comment]
bitte mal einen Report Melden, also wenn die Absturzmeldung kommt auf Melden gehen und kuze Beschreibung dazu

**Comment by Dietmar-Franken** [comment]
ok, mach ich später

**Comment by Dietmar-Franken** [comment]
Im Moment bekomme ich es nicht mehr reproduziert.Hab es mit S4,S5,S6 edge versucht,nichts.Aber werde es morgen noch mal versuchen.Heute Morgen ist das bestimmt 5 mal passiert. :-(

**Comment by agent4788** [comment]
Ich habe jetzt mal ein wenig in der VM gespielt und dabei Räume erstellt und gelöscht. Beim erstellen und aktualisieren konnte ich nichts feststellen, nur beim löschen schmiert die APP ab wenn man gerade mit der APP in dem gelöschten Raum ist und danach in einen anderen wechselt.

12-09 06:53:13.480 4363-4363/de.rpi_controlcenter.shc E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: de.rpi_controlcenter.shc, PID: 4363
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
                                                                            at android.widget.Toast.makeText(Toast.java:285)
                                                                            at de.rpi_controlcenter.shc.Fragment.RoomViewFragment$2$1$1.run(RoomViewFragment.java:144)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5257)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by Dietmar-Franken** [comment]
Gerade wieder passiert.Chrashreport geschickt.

**Comment by agent4788** [comment]
Sehr gut, jetzt habe ich den Trace dazu. Der Fehler wurde schon ein paar mal gemeldet und sollte eigentlich in Version 1.0.3 behoben sein. Ich suche nochmal woran es noch hängt.
